[package]
name = "adroit"
version = "0.3.0"
publish = false
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
enumset = "1"
index_vec = "0.1"
indexmap = "2"
itertools = "0.14"
line-index = "0.1"
logos = "0.15"
wasm-encoder = "0.230"
