name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: cargo test

  vscode:
    strategy:
      fail-fast: false
      matrix:
        include:
          - vscode-platform: win32-x64
            rust-target: x86_64-pc-windows-gnu
            github-os: ubuntu-22.04
            ext: ".exe"
            install-script: sudo apt-get install -y mingw-w64
          - vscode-platform: linux-x64
            rust-target: x86_64-unknown-linux-musl
            github-os: ubuntu-22.04
            ext: ""
            install-script: ""
          - vscode-platform: darwin-x64
            rust-target: x86_64-apple-darwin
            github-os: macos-13
            ext: ""
            install-script: ""
          - vscode-platform: darwin-arm64
            rust-target: aarch64-apple-darwin
            github-os: macos-14
            ext: ""
            install-script: ""
    runs-on: ${{ matrix.github-os }}
    steps:
      - uses: actions/checkout@v4
      - run: ${{ matrix.install-script }}
      - run: rustup target add ${{ matrix.rust-target }}
      - run: npm ci
      - run: cargo build --release --target ${{ matrix.rust-target }}
      - run: mkdir packages/vscode/bin
      - run: cp target/${{ matrix.rust-target }}/release/adroit${{ matrix.ext }} packages/vscode/bin/adroit${{ matrix.ext }}
      - run: npm run --workspace=adroit-vscode build -- --target ${{ matrix.vscode-platform }}
      - uses: actions/upload-artifact@v4
        with:
          name: adroit-vscode-${{ matrix.vscode-platform }}
          path: packages/vscode/adroit-vscode-*.vsix
